---
- hosts: 172.31.82.36
  become: yes
  tasks: 
   - include_tasks: myfile.yml

   - name: I want to copy the file from Ansible master to nodes
     copy:
       src: mystatic
       dest: /home/ubuntu/mystaticfile

   - name: I want to install webserver
     apt:
      name: apache2
      state: present   

   - name: copy dynamic file in to node side
     template: 
         src: myindexfile.j2
         dest: /var/www/html/index.html    