---
- hosts: 172.31.82.36
  become: yes
  tasks: 
   - include_tasks: myfile.yml

   - name: I want to copy the file from Ansible master to nodes
     copy:
       src: mystatic
       dest: /home/ubuntu/mystaticfile