---
- hosts: 172.31.82.36
  become: yes
  tasks:
   - name: I want to install multi package
     apt:
      name: "{{ item }}"
      state: present
     loop:
       - git
       - tree
       - wget  

