---
- hosts: all
  become: yes
  gather_facts: yes
  tasks: 
  - name: I Want to install webserver on ansible node side
    apt: 
      name: apache2
      state: present
      when: ansible_os_family == "Debian"

  - name: I want to start webserver
    service: 
      name: apache2
      state: started
      when: ansible_os_family =="Debian"
    
